(4) Heartbeat thread connected to PLC. Writing 'Heartbeat' high every 1 second

(3) Heartbeat thread connected to PLC. Writing 'Heartbeat' high every 1 second

Exception in thread 4_heartBeat:
Traceback (most recent call last):
  File "C:\Users\keyence-user\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
(5) Heartbeat thread connected to PLC. Writing 'Heartbeat' high every 1 second

    self.run()
Exception in thread 3_heartBeat:
  File "C:\Users\keyence-user\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
Traceback (most recent call last):
Exception in thread 5_heartBeat:
  File "C:\Users\keyence-user\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
Traceback (most recent call last):
  File "C:\Users\keyence-user\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "c:\BET_Housing_Python\BET_Housing\main copy.py", line 218, in heartbeat
    self.run()
  File "C:\Users\keyence-user\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self.run()
    while not (kill_threads.is_set() or reset_event.is_set()):
  File "C:\Users\keyence-user\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
                                        ^^^^^^^^^^^^^^^^^^
    self._target(*self._args, **self._kwargs)
AttributeError: 'dict' object has no attribute 'is_set'
  File "c:\BET_Housing_Python\BET_Housing\main copy.py", line 218, in heartbeat
    self._target(*self._args, **self._kwargs)
  File "c:\BET_Housing_Python\BET_Housing\main copy.py", line 218, in heartbeat
    while not (kill_threads.is_set() or reset_event.is_set()):
                                        ^^^^^^^^^^^^^^^^^^
    while not (kill_threads.is_set() or reset_event.is_set()):
AttributeError: 'dict' object has no attribute 'is_set'
                                        ^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'is_set'
(5) Sequence Started
(5) Connecting to PLC at 120.123.249.82
(5) Connected to Keyence at 172.19.147.82
(3) Sequence Started
(3) Connecting to PLC at 120.123.249.82
(3) Connected to Keyence at 172.19.145.80


(4) Sequence Started
(4) Connecting to PLC at 120.123.249.82
(4) Connected to Keyence at 172.19.146.81

(5) ...PLC Connection Successful...

(3) ...PLC Connection Successful...



(4) ...PLC Connection Successful...

(5) Flushing PLC(Result) tag data...


(3) Flushing PLC(Result) tag data...
(5) Reading PLC



(3) Reading PLC

(5) Stage 0: Awaiting PLC(LOAD_PROGRAM) and PLC(BUSY) state changes...

(4) Flushing PLC(Result) tag data...
(3) Stage 0: Awaiting PLC(LOAD_PROGRAM) and PLC(BUSY) state changes...

(5) Setting Boolean Tags for Stage 0
(4) Reading PLC



(3) Setting Boolean Tags for Stage 0
Exception in thread machine_5:
Traceback (most recent call last):

  File "C:\Users\keyence-user\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
(4) Stage 0: Awaiting PLC(LOAD_PROGRAM) and PLC(BUSY) state changes...
Exception in thread machine_3:
(4) Setting Boolean Tags for Stage 0
Traceback (most recent call last):

    self.run()
  File "C:\Users\keyence-user\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\Users\keyence-user\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
Exception in thread machine_4:
    self.run()
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
  File "C:\Users\keyence-user\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\Users\keyence-user\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
  File "c:\BET_Housing_Python\BET_Housing\main copy.py", line 98, in cycle
    self.run()
  File "C:\Users\keyence-user\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    if (kill_threads.is_set() or reset_events[current_thread].is_set()):
    self._target(*self._args, **self._kwargs)
                                              ^^^^^^^^^^^^^^
  File "c:\BET_Housing_Python\BET_Housing\main copy.py", line 98, in cycle
UnboundLocalError: cannot access local variable 'current_thread' where it is not associated with a value
    self._target(*self._args, **self._kwargs)
  File "c:\BET_Housing_Python\BET_Housing\main copy.py", line 98, in cycle
    if (kill_threads.is_set() or reset_events[current_thread].is_set()):
                                              ^^^^^^^^^^^^^^
    if (kill_threads.is_set() or reset_events[current_thread].is_set()):
                                              ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'current_thread' where it is not associated with a value
UnboundLocalError: cannot access local variable 'current_thread' where it is not associated with a value
Traceback (most recent call last):
  File "c:\BET_Housing_Python\BET_Housing\main copy.py", line 256, in <module>
    main()
  File "c:\BET_Housing_Python\BET_Housing\main copy.py", line 244, in main
    reset_event = reset_events[cycle_thread]
                  ~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: <Thread(machine_3, stopped 8040)>
PS C:\BET_Housing_Python\BET_Housing> 